[package]
name = "essimport"
version = "0.1.0"
authors = ["Orest Dubay <orest3.dubay@gmail.com>"]

[dependencies]
xml-rs = "0.8.4"
clap = { version = "3.0.5", features = ["derive"] }
zip = "0.5.13"
rustc-serialize = "0.3"
rusqlite = "0.26.3"

[features]
bundled = []